server:
  port: ${PORT:8080}
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
  sso:
    login-route: /oauth2/authorization/{provider-id}
