logging:
  level:
    root: info
    org:
      atmosphere: warn
server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application
